server:
  port: 8081
spring:
  application:
    name: ribbon-order
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: localhost:8848
        # 集群名称
        cluster-name: BJ-SERVER
        namespace: deca330d-ad01-4b04-9938-3b41221bc886
        metadata:
          current-version: v1
# Ribbon开启饥饿记载模式，避免重启服务后第一次调用超时
ribbon:
  eager-load:
    enabled: true
    clients: ribbon-product
# Ribbon负载均衡策略:
#   1) com.netflix.loadbalancer.RandomRule：随机。
#   2) RetryRule：重试。先按照轮询策略获取服务，如果获取失败则在指定时间内重试，获取可用服务。
#   3) RoundRobinRule：轮询。
#   4) AvailabilityFilteringRule：会先过滤掉由于多次访问故障而处于断路器跳闸状态的服务，还有并发的连接数超过阈值的服务，然后对剩余的服务列表进行轮询。
#   5) WeightedResponseTimeRule：权重。根据平均响应时间计算所有服务的权重，响应时间越快服务权重越大被选中的概率越高。刚启动时，如果统计信息不足，则使用轮询策略，等信息足够，切换到 WeightedResponseTimeRule
#   6) BestAvailableRule：选过滤掉多次访问故障而处于断路器跳闸状态的服务，然后选择一个并发量最小的服务
#   7) ZoneAvoidanceRule：符合判断server所在区域的性能和server的可用性选择服务
ribbon-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.dream.spring.cloud.ribbon.order.rule.CustomSameClusterVersionRule
