server:
  port: 8085
spring:
  application:
    name: ribbon-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: NJ-SERVER
        namespace: deca330d-ad01-4b04-9938-3b41221bc886
        metadata:
          current-version: v2
